name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: CI=false npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY || 'AIzaSyClw7-J5-dWAxzGX75MKNpOLGT-GQkFBzs' }}
          REACT_APP_FIREBASE_PROJECT_ID: "rc-exp-check-in"
          REACT_APP_FIREBASE_DATABASE_URL: "https://rc-exp-check-in-default-rtdb.firebaseio.com"
          
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RC_EXP_CHECK_IN }}'
          channelId: live
          projectId: rc-exp-check-in
